Octothorpes/Atelier

- .eslintignore
created a .eslintignore file to resolve all of our flagged errors from the bundle.js file
> added .eslintignore file for the bundle.js file errors

- client/src/components/RnR/ReviewsButtons.jsx
- client/src/components/RnR/ReviewsFooter.jsx
- client/src/components/RnR/ReviewsPhotos.jsx
- client/src/components/RnR/RnR.jsx
- client/src/components/RnR/modals/ImageModal.jsx
- client/src/components/RnR/modals/modals.css
- package-lock.json
- built the image modals so images expand on click and shrink back to thumbnail on exit
- Ash showed me how to add the onClick HOC tracker so i implemented that on several functions
> photo modals built and completely functional

- client/src/components/App.jsx
- client/src/components/RnR/RatingsComfort.jsx
- client/src/components/RnR/RatingsFit.jsx
- client/src/components/RnR/RatingsLength.jsx
- client/src/components/RnR/RatingsQuality.jsx
- client/src/components/RnR/RatingsSize.jsx
- client/src/components/RnR/RatingsWidth.jsx
- client/src/components/RnR/Reviews.jsx
- client/src/components/RnR/ReviewsButtons.jsx
- client/src/components/RnR/ReviewsTiles.jsx
- client/src/components/RnR/RnR.css
- client/src/components/RnR/RnR.jsx
- client/src/components/RnR/modals/AddReviewModal.jsx
- client/src/components/RnR/modals/modals.css
- created a basic 'add a review' modal
- added a 'productName' key to the root App.jsx state to pass down to my prop for the modal
- all basic requirements are present
- modal is not yet dynamic and needs to be built out further
current image
> created a basic 'add a review' modal

- client/src/components/QnA/QuestionsList.jsx
- client/src/components/QnA/QuestionsNAnswersContainer.jsx
- client/src/components/QnA/SearchQuestions.jsx
1. Add functionality to filter questions based on search text
2. Display the questions based on Helpfulness (Descending order)
> Add search functionality and sort question bases on helpfulness

- client/src/components/App.jsx
- client/src/components/RnR/Reviews.jsx
- client/src/components/RnR/ReviewsButtons.jsx
- client/src/components/RnR/RnR.css
- client/src/components/RnR/modals/AddReviewModal.jsx
- client/src/components/RnR/modals/components/ModalCharacs.jsx
- client/src/components/RnR/modals/components/ModalReviewBody.jsx
- client/src/components/RnR/modals/components/ModalStars.jsx
- client/src/components/RnR/modals/components/ModalUpload.jsx
- client/src/components/RnR/modals/modals.css
- the 'add a review' modal is now dynamic and follows bus docs guidelines
- next steps will be a field check and then a post request on successful field check
- CSS has not been implemented and im trying to do better at holding off to focus on functionality
> Create modals add review2

- client/src/components/ProductDetail/ProductDetailStyles.css
- client/src/components/ProductDetail/imageGallery.jsx
- client/src/components/ProductDetail/productInformation.jsx
Changes - 
Image thumbnail highlights on select 
If image is not in view it will auto scroll to the image - there are css issues that need to be fixed with this, but i'm pretty sure how to do it and it isn't a crazy priority right now 
up and down left and right buttons work and will  execute scrolling functionality above 
on hover  over the main image a magnifying glass will appear.  
- the issue with this is also css related, I need to position the left and right arrows on the grid instead of in a div box, because when the div box is on top of the image,  meaning the magnifying glass cursor disappears. Also have a good idea of how to fix this but not a high priority .  
Thanks Guys 
======= 
EDIT 
I also would like to make the image bigger  eventually and get the spacing of the …
> Default image2

- client/src/components/App.jsx
- client/src/components/RnR/Reviews.css
- client/src/components/RnR/Reviews.jsx
- client/src/components/RnR/ReviewsCountDropdown.jsx
- client/src/components/RnR/ReviewsFooter.jsx
- client/src/components/RnR/ReviewsTiles.jsx
- client/src/components/RnR/RnR.css
- client/src/components/RnR/RnR.jsx
- client/src/components/defaultState.js
- implemented the functionality that allows you to sort reviews after selections of the 'sort on' dropdown menu
- implemented a scroll bar to maintain screen space when review tiles become too large or if there are many reviews
- there is still a bug with the Helpfulness and Report buttons that needs to be fixed
current image:
> Sort reviews ability complete

- client/src/components/ProductDetail/galleryModal.jsx
- client/src/components/ProductDetail/galleryModalStyles.css
- client/src/components/ProductDetail/imageGallery.jsx
- client/src/components/ProductDetail/productDetailContainer.jsx
- client/src/components/ProductDetail/productInformation.jsx
- client/src/fa-icons/fa-icons.js
Hey guys. 
Images are mostly complete aside from zoom functionality. Clicking the Image opens the expanded modal and you can filter through it.
Sizing is an issue but its all on a grid so I just need to change the top level element. 
Styling in general will be addressed later , such as the buttons and what not.
I also added some fa icons and ensured the server setup Ash reconfigured works. 
Thanks , see you guys tomorrow.
> Image modal

- client/src/components/HOC/withInteractionApi.jsx
- client/src/components/QnA/ErrorMessage.jsx
- client/src/components/QnA/Modals/AddNewAnswer.css
- client/src/components/QnA/Modals/AddNewAnswer.jsx
- client/src/components/QnA/Modals/AddNewQuestion.jsx
- client/src/components/QnA/Modals/AddQuestionModal.css
- client/src/components/QnA/Question.jsx
- client/src/components/QnA/QuestionsList.jsx
- client/src/components/QnA/SearchQuestions.jsx
- server.js
This pr has the following changes.
1. Add error handling of the modals.
2. Now user can successfully add a new question and also post a new answer
> Modal error handling and api setup

- client/src/components/App.jsx
- client/src/components/RnR/Ratings.css
- client/src/components/RnR/Ratings.jsx
- client/src/components/RnR/RatingsBarChart.jsx
- client/src/components/RnR/Reviews.jsx
- client/src/components/RnR/ReviewsTiles.jsx
- client/src/components/RnR/RnR.css
- client/src/components/RnR/RnR.jsx
- the star bar chart now acts as a filter as well
current image
> Sort by star click

- client/src/components/ProductDetail/addToCart.jsx
- client/src/components/ProductDetail/galleryModal.jsx
- client/src/components/ProductDetail/galleryModalStyles.css
- client/src/components/ProductDetail/imageGallery.jsx
- client/src/components/ProductDetail/productInformation.jsx
- client/src/components/ProductDetail/sizeAndQuantitySelector.jsx
- client/src/components/ProductDetail/styleSelector.jsx
- client/src/components/ProductDetail/styleSelector.test.js
Changes 
All components that need click interactions are wrapped and working. 
- changed button styling CSS to only apply to my button. 
Thanks guys!
> Wrapping product detail

- client/src/components/App.jsx
- client/src/components/RelatedProducts/OutfitProducts.jsx
- client/src/components/RelatedProducts/RP.css
- client/src/components/RelatedProducts/RelatedProducts.jsx
- client/src/components/RnR/Reviews.jsx
- client/src/components/RnR/ReviewsButtons.jsx
- client/src/components/RnR/ReviewsCountDropdown.jsx
- client/src/components/RnR/ReviewsFooter.jsx
- client/src/components/RnR/ReviewsPhotos.jsx
- client/src/components/RnR/RnR.jsx
- client/src/components/RnR/modals/AddReviewModal.jsx
- client/src/components/RnR/modals/components/ModalCharacs.jsx
- client/src/components/RnR/modals/components/ModalReviewBody.jsx
- client/src/components/RnR/modals/components/ModalUpload.jsx
- fixed the Related Products widget to css align with ours
- wrapped all clickable components with HOC
> InvokeHOCs - complete wrapping onClicks

- client/src/components/App.jsx
- client/src/components/ProductDetail/ProductDetailStyles.css
- server.js
Hey Guys, 
Just added  the ratings and reviews to the server , so when the url changes, we'll get  4 pieces of data at once. 
Aaron has a little debugging to do with the star ratings, but we're close. 
Thanks!
> ratings and reviews gathered on mount

- client/dist/index.html
- client/src/components/ProductDetail/ProductDetailStyles.css
- client/src/components/ProductDetail/addToCart.test.js
- client/src/components/ProductDetail/features.test.js
- client/src/components/ProductDetail/galleryModal.jsx
- client/src/components/ProductDetail/imageGallery.jsx
- client/src/components/ProductDetail/productDescriptionAndFeatures.jsx
- client/src/components/ProductDetail/productInformation.jsx
- client/src/components/ProductDetail/productInformation.test.js
- client/src/components/ProductDetail/productInformationMockProps.js
- client/src/components/ProductDetail/sizeAndQuantitySelector.test.js
- client/src/components/ProductDetail/styleSelector.jsx
Hey Guys, 
I improved our accessibility metrics by adding some alt tags and aria-labels on buttons with no text. I also added a lang attribute to our main html and that seemed to help alot. 
I also added a lot of code for test and was utterly frustrated by it. It doesn't do anything to your code , I just ended up branching this off a test writing branch so thats why its in there. 
- also added the anchor to Aarons Component  so You can click on the reviews link and it navigates down. Thanks Aaron!
> Accessibility

- client/src/components/App.jsx
- client/src/components/ProductDetail/productInformation.jsx
- client/src/components/RnR/Ratings.css
- client/src/components/RnR/Ratings.jsx
- client/src/components/RnR/RatingsBarChart.jsx
- client/src/components/RnR/RatingsComfort.jsx
- client/src/components/RnR/RatingsFit.jsx
- client/src/components/RnR/RatingsLength.jsx
- client/src/components/RnR/RatingsQuality.jsx
- client/src/components/RnR/RatingsSize.jsx
- client/src/components/RnR/RatingsWidth.jsx
- client/src/components/RnR/ReviewsCountDropdown.jsx
- client/src/components/RnR/RnR.css
- client/src/components/RnR/RnR.jsx
- due to the API data being inaccurate for my reviews data, i had to create a 'workaround' to render more accurate data
- everything boxed below in my image is what i created new algorithms for to better represent the data
- also added additional css
> Fixed Calculations

- client/src/components/App.jsx
- client/src/components/RnR/Ratings.css
- client/src/components/RnR/Ratings.jsx
- client/src/components/RnR/RatingsBarChart.jsx
- client/src/components/RnR/Reviews.css
- client/src/components/RnR/Reviews.jsx
- client/src/components/RnR/ReviewsButtons.jsx
- client/src/components/RnR/ReviewsTiles.jsx
- client/src/components/RnR/RnR.jsx
- fixed how stars are loaded for our default product
- fixed the count for the 'more reviews' button
- brought down a formula through props from the app.jsx file
> Additional fixes

- client/src/components/ProductDetail/ProductDetailStyles.css
- client/src/components/ProductDetail/galleryModalStyles.css
- client/src/components/ProductDetail/imageGallery.jsx
- client/src/components/ProductDetail/productDetailContainer.jsx
Hey guys, 
- Fixed some css issues with the add to cart button 
- fixed the scrollbar issue where the buttons werent displayed properly 
- fixed the hover issue where the mag glass wasn't appearing in the center 
- added  pointer cursor when hovering over thumbnails in default view 
- fixed breaking bug by displaying the above photo if there is no product styles 
Still have to work on some spacing stuff, but its much better.
> Fix css product detail

- client/src/components/App.jsx
- client/src/components/QnA/Modals/AddNewAnswer.jsx
- client/src/components/QnA/Question.jsx
- client/src/components/QnA/QuestionsList.jsx
- client/src/components/QnA/QuestionsNAnswersContainer.jsx
- client/src/components/QnA/SearchQuestions.jsx
1. Fixed a bug on the search component
2. QnA widget will. not appear if the product styles are empty
3. Fixed a bug in the Answers Modal
> Fix bug search

- client/src/components/RnR/Ratings.jsx
- client/src/components/RnR/RatingsArrowCharts.jsx
- client/src/components/RnR/ReviewsBody.jsx
- client/src/components/RnR/ReviewsPhotos.jsx
- client/src/components/RnR/ReviewsRateDate.jsx
- client/src/components/RnR/ReviewsTiles.jsx
- client/src/components/RnR/RnR.test.js
- created error handling for usernames and review summaries longer than 60 characters
- added error handling for arrow charts when reviews do not exist but meta data does
- added error handling for images that are not rendered properly
- added jest test 
- reorganized the review tiles when there is a response from the seller, this now appears under uploaded images
> Additional fixes7

- client/src/components/QnA/Answer.test.js
- client/src/components/QnA/Modals/AddNewAnswer.jsx
- client/src/components/QnA/Modals/AddNewAnswer.test.js
- client/src/components/QnA/Modals/AddNewQuestion.jsx
- client/src/components/QnA/Modals/AddNewQuestion.test.js
- client/src/components/QnA/Modals/ImageModal.test.js
- client/src/components/QnA/Question.jsx
- client/src/components/QnA/Questions.test.js
- client/src/components/QnA/QuestionsNAnswersContainer.test.js
- client/src/components/QnA/SearchQuestion.test.js
- client/src/components/QnA/SearchQuestions.jsx
1. Added unit tests
2. Small refactoring
> Unit tests
